#spring:
#  datasource:
#    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}
#    username: root
#    password: root
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/note_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8089
