spring:
  data:
    mongodb:
#      username: ${MONGO_USERNAME}
#      password: ${MONGO_PASSWORD}
#      database: ${MONGO_DATABASE}
#      port: ${MONGO_PORT}
#      host: ${MONGO_HOST}
      database: notedb
      port: 27017
      host: localhost
  application:
    name: note-service
server:
  port: 8082
