#spring:
#  data:
#    mongodb:
 #     authentication-database:
#      username: ${MONGO_USERNAME}
#      password: ${MONGO_PASSWORD}
#      database: ${MONGO_DATABASE}
#      port: ${MONGO_PORT}
#      host: ${MONGO_HOST}
spring:
  data:
    mongodb:
 #     authentication-database:
 #     username: root
 #     password: root
      database: notedb
      port: 27017
      host: localhost
  application:
    name: category-service
server:
  port: 8083
